name: KeywordHanaro CI/CD
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  test-build:
    if: github.event_name == 'pull_request' # PR 이벤트에서만 실행
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List files
        run: ls -R

      - name: Create resources directory
        run: mkdir -p ./src/main/resources

      - name: Set properties
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      - name: Grant executable permissions for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: List files
        run: ls -R

      - name: Create resources directory
        run: mkdir -p ./src/main/resources

      - name: set props
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.properties

      - name: grant exe
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew clean build

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: scp jar to was
        run: |
          scp build/libs/*.jar ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/keywordhanaro.jar

      - name: restart spring
        run: |
          ssh ec2-user@${{ secrets.WAS }} '
          cd /home/ec2-user/workspace &&
          sudo systemctl restart springboot
          '
